package simpledb;

import java.util.*;
import java.io.*;

/**
 * Each instance of HeapPage stores data for one page of HeapFiles and
 * implements the Page interface that is used by BufferPool.
 *
 * @see HeapFile
 * @see BufferPool
 *
 */
public class HeapPage implements Page {

    HeapPageId pid;
    TupleDesc td;
    byte header[];
    Tuple tuples[];
    int numSlots;

    byte[] oldData;

    TransactionId dirtyTransactionID;

    /**
     * Create a HeapPage from a set of bytes of data read from disk.
     * The format of a HeapPage is a set of header bytes indicating
     * the slots of the page that are in use, some number of tuple slots.
     *  Specifically, the number of tuples is equal to: <p>
     *          floor((BufferPool.PAGE_SIZE*8) / (tuple size * 8 + 1))
     * <p> where tuple size is the size of tuples in this
     * database table, which can be determined via {@link Catalog#getTupleDesc}.
     * The number of 8-bit header words is equal to:
     * <p>
     *      ceiling(no. tuple slots / 8)
     * <p>
     * @see Database#getCatalog
     * @see Catalog#getTupleDesc
     * @see BufferPool#PAGE_SIZE
     */
    public HeapPage(HeapPageId id, byte[] data) throws IOException {
        this.pid = id;
        this.td = Database.getCatalog().getTupleDesc(id.getTableId());
        this.numSlots = getNumTuples();
        DataInputStream dis = new DataInputStream(new ByteArrayInputStream(data));

        // allocate and read the header slots of this page
        header = new byte[getHeaderSize()];
        for (int i=0; i<header.length; i++)
            header[i] = dis.readByte();

        try{
            // allocate and read the actual records of this page
            tuples = new Tuple[numSlots];
            for (int i=0; i<tuples.length; i++)
                tuples[i] = readNextTuple(dis,i);
        }catch(NoSuchElementException e){
            e.printStackTrace();
        }
        dis.close();

        setBeforeImage();
    }

    /** Retrieve the number of tuples on this page.
     @return the number of tuples on this page
     */
    private int getNumTuples() {
        return (int) Math.floor(BufferPool.PAGE_SIZE * 8 / (td.getSize() * 8 + 1));
    }

    /**
     * Computes the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     * @return the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     */
    private int getHeaderSize() {
        return (int ) Math.ceil((double)numSlots/8);
    }

    /** Return a view of this page before it was modified
     -- used by recovery */
    public HeapPage getBeforeImage(){
        try {
            return new HeapPage(pid,oldData);
        } catch (IOException e) {
            e.printStackTrace();
            //should never happen -- we parsed it OK before!
            System.exit(1);
        }
        return null;
    }

    public void setBeforeImage() {
        oldData = getPageData().clone();
    }

    /**
     * @return the PageId associated with this page.
     */
    public HeapPageId getId() {
        return pid;
        //throw new UnsupportedOperationException("implement this");
    }

    /**
     * Suck up tuples from the source file.
     */
    private Tuple readNextTuple(DataInputStream dis, int slotId) throws NoSuchElementException {
        // if associated bit is not set, read forward to the next tuple, and
        // return null.
        if (!isSlotUsed(slotId)) {
            for (int i=0; i<td.getSize(); i++) {
                try {
                    dis.readByte();
                } catch (IOException e) {
                    throw new NoSuchElementException("error reading empty tuple");
                }
            }
            return null;
        }

        // read fields in the tuple
        Tuple t = new Tuple(td);
        RecordId rid = new RecordId(pid, slotId);
        t.setRecordId(rid);
        try {
            for (int j=0; j<td.numFields(); j++) {
                Field f = td.getFieldType(j).parse(dis);
                t.setField(j, f);
            }
        } catch (java.text.ParseException e) {
            e.printStackTrace();
            throw new NoSuchElementException("parsing error!");
        }

        return t;
    }

    /**
     * Generates a byte array representing the contents of this page.
     * Used to serialize this page to disk.
     * <p>
     * The invariant here is that it should be possible to pass the byte
     * array generated by getPageData to the HeapPage constructor and
     * have it produce an identical HeapPage object.
     *
     * @see #HeapPage
     * @return A byte array correspond to the bytes of this page.
     */
    public byte[] getPageData() {
        int len = BufferPool.PAGE_SIZE;
        ByteArrayOutputStream baos = new ByteArrayOutputStream(len);
        DataOutputStream dos = new DataOutputStream(baos);

        // create the header of the page
        for (int i=0; i<header.length; i++) {
            try {
                dos.writeByte(header[i]);
            } catch (IOException e) {
                // this really shouldn't happen
                e.printStackTrace();
            }
        }

        // create the tuples
        for (int i=0; i<tuples.length; i++) {

            // empty slot
            if (!isSlotUsed(i)) {
                for (int j=0; j<td.getSize(); j++) {
                    try {
                        dos.writeByte(0);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }
                continue;
            }

            // non-empty slot
            for (int j=0; j<td.numFields(); j++) {
                Field f = tuples[i].getField(j);
                try {
                    f.serialize(dos);

                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        // padding
        int zerolen = BufferPool.PAGE_SIZE - (header.length + td.getSize() * tuples.length); //- numSlots * td.getSize();
        byte[] zeroes = new byte[zerolen];
        try {
            dos.write(zeroes, 0, zerolen);
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            dos.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return baos.toByteArray();
    }

    /**
     * Static method to generate a byte array corresponding to an empty
     * HeapPage.
     * Used to add new, empty pages to the file. Passing the results of
     * this method to the HeapPage constructor will create a HeapPage with
     * no valid tuples in it.
     *
     * @return The returned ByteArray.
     */
    public static byte[] createEmptyPageData() {
        int len = BufferPool.PAGE_SIZE;
        return new byte[len]; //all 0
    }

    /**
     * Delete the specified tuple from the page;  the tuple should be updated to reflect
     *   that it is no longer stored on any page.
     * @throws DbException if this tuple is not on this page, or tuple slot is
     *         already empty.
     * @param t The tuple to delete
     */
    public void deleteTuple(Tuple t) throws DbException {
        if (!isSlotUsed(t.getRecordId().tupleno()))
            throw new DbException("No such tuple");
        if (t.getRecordId().getPageId() != pid)
            throw new DbException("No such tuple");

        markSlotUsed(t.getRecordId().tupleno(), false);
    }

    /**
     * Adds the specified tuple to the page;  the tuple should be updated to reflect
     *  that it is now stored on this page.
     * @throws DbException if the page is full (no empty slots) or tupledesc
     *         is mismatch.
     * @param t The tuple to add.
     */
    public void insertTuple(Tuple t) throws DbException {
        if (getNumEmptySlots() == 0)
            throw new DbException("Page full");
        for (int i =0; i<numSlots; i++){
            if (!isSlotUsed(i)) {
                t.setRecordId(new RecordId(pid, i));
                markSlotUsed(i, true);
                tuples[i] = t;
                return;
            }
        }

        /*
        for (int i =0 ; i < header.length ; i++) {
            if (header[i] != 127) {
                Byte b = header[i];
                for (int j = 0; j <8; j ++){
                    if ((b >> 7-(i % 8)) % 1 == 0) {
                        t.setRecordId(new RecordId(pid, i * 8 + j));
                        markSlotUsed(i * 8 + j, true);
                        markSlotUsed(i * 8 + j, true);
                        return;
                    }
                }
            }
        }
        */
    }

    /**
     * Marks this page as dirty/not dirty and record that transaction
     * that did the dirtying
     */
    public void markDirty(boolean dirty, TransactionId tid) {
        if (dirty)
            this.dirtyTransactionID = tid;
        else
            this.dirtyTransactionID = null;
    }

    /**
     * Returns the tid of the transaction that last dirtied this page, or null if the page is not dirty
     */
    public TransactionId isDirty() {
        return dirtyTransactionID;
    }

    /**
     * Returns the number of empty slots on this page.
     */
    public int getNumEmptySlots() {
        //referenced from http://stackoverflow.com/questions/12310017/how-to-convert-a-byte-to-its-binary-string-representation
        int filledSlots = 0;
        for (Byte b : header) {
            String bits = String.format("%8s", Integer.toBinaryString(b & 0xFF)).replace(' ', '0');
            for (int i = 0; i < 8; i++) {
                if (bits.substring(7-(i % 8),7-(i % 8)+1).equals("1"))
                    filledSlots++;
            }
        }
        return numSlots - filledSlots;
    }

    /**
     * Returns true if associated slot on this page is filled.
     */
    public boolean isSlotUsed(int i) {
        Byte b = header[i/8];
        String bits = String.format("%8s", Integer.toBinaryString(b & 0xFF)).replace(' ', '0');
        if (bits.substring(7-(i % 8),7-(i % 8)+1).equals("1"))
            return true;
        return false;
    }

    /**
     * Abstraction to fill or clear a slot on this page.
     */
    private void markSlotUsed(int i, boolean value) {
        Byte b = header[i/8];
        if (value) {
            b = (byte) (b | (1 << (i % 8)));
        } else {
            b = (byte) (b & ~(1 << (i % 8)));
        }
        header[i/8] = b;


        //String bits = String.format("%8s", Integer.toBinaryString(b & 0xFF)).replace(' ', '0');

        //String binaryString = bits.substring(0, 7-(i % 8)) +(value ? "1" : "0") +  bits.substring(7-(i % 8)+1,8);
        //System.out.println(binaryString);

        //header[i/8] = Byte.parseByte(binaryString, 2);
    }

    /**
     * @return an iterator over all tuples on this page (calling remove on this iterator throws an UnsupportedOperationException)
     * (note that this iterator shouldn't return tuples in empty slots!)
     */
    public Iterator<Tuple> iterator() {
        /*
        Iterator<Tuple> it = new Iterator<Tuple>() {
            final int tupleNumSlots = numSlots;
            private int currentIndex = 0;

            @Override
            public boolean hasNext() {

                if (currentIndex >= numSlots){
                    return false;}

                do {
                    if (isSlotUsed(currentIndex))
                        return true;
                    currentIndex++;

                } while (currentIndex < numSlots);

                return false;
            }

            @Override
            public Tuple next() throws  NoSuchElementException{
                System.out.println(hasNext());

                if (currentIndex >= numSlots)
                    throw new NoSuchElementException();
                int current;

                if (isSlotUsed(currentIndex)) {
                    current = currentIndex;
                    currentIndex++;
                } else {
                    while (currentIndex < numSlots) {
                        currentIndex++;
                        if (isSlotUsed(currentIndex))
                            break;
                    }
                    if (currentIndex >= numSlots)
                        throw new NoSuchElementException();

                    current = currentIndex;
                    currentIndex++;
                }

                System.out.println(tuples[current]);
                return tuples[current];
            }

            @Override
            public void remove() {
                throw new UnsupportedOperationException();
            }
        };
        return it;
        */

        Iterator<Tuple> tupleIterator = new Iterator<Tuple>() {

            //keeps track of the position
            int ticker = 0;

            @Override
            public boolean hasNext() {
                // if we have more than the designated number of tuples, return false
                if(ticker >= numSlots){
                    return false;
                }
                // loop throug the header and find a true
                for(int i = ticker; i < numSlots; i++ ){
                    if(isSlotUsed(i)){
                        return true;
                    }
                }
                return false;
            }

            @Override
            public Tuple next() {
                int flag = 0;
                Tuple tuple;
                if(!hasNext()){
                    throw new NoSuchElementException();
                }
                //if we have a tuple at our current spot, return it
                else if (isSlotUsed(ticker)) {
                    flag = ticker;
                }
                // if we don't have something at our current spot, keep on searching
                else{
                    for(int i = ticker; i < numSlots; i++){
                        if(isSlotUsed(i)){
                            flag = i;
                            break;
                        }
                    }
                }
                tuple = tuples[flag];
                ticker++;
                return tuple;
            }

            public void remove(){

            }
        };
        return tupleIterator;
    }

}

